name = "keypadder"
description = "Programmable virtual keypad for your Linux desktop"
version = "0.1.0-dev"
tags = ["linux", "keyboard", "mobile", "programmable", "tablet", "macro", "keypad", "macropad"]

authors = ["Stephen Merrony"]
maintainers = ["Stephen Merrony <merrony@gmail.com>"]
maintainers-logins = ["SMerrony"]

executables = ["keypadder"]
[[depends-on]]
aws = "^23.0.0"
[[depends-on]]
ada_toml = "~0.3.0"
