[keypadder]
port = 8082	# HTTP port to use

[[tab]]   # A new tab
label = "French"
cols = 3	# No. of columns on this tab
keys = [
  { label = "&agrave;", send = "RIGHTALT,GRAVE,A" },
  { label = "&acirc;",  send = "RIGHTALT,^6,A" },
  { label = "&ccedil;", send = "RIGHTALT,COMMA,C" },
# new row will start here
  { label = "&egrave;", send = "RIGHTALT,GRAVE,E" },
  { label = "&ecirc;",  send = "RIGHTALT,^6,E" },
  { label = "&eacute;", send = "RIGHTALT,APOSTROPHE,E" },
#
  { label = "&igrave;", send = "RIGHTALT,GRAVE,I" },
  { label = "&icirc;",  send = "RIGHTALT,^6,I" },
  { label = "&iuml;",   send = "RIGHTALT,^2,I" },
#
  { label = "&ograve;", send = "RIGHTALT,GRAVE,O" },
  { label = "&ocirc;",  send = "RIGHTALT,^6,O" },
  { label = "&euml;",   send = "RIGHTALT,^2,E" },
#
  { label = "&ugrave;", send = "RIGHTALT,GRAVE,U" },
  { label = "&ucirc;",  send = "RIGHTALT,^6,U" },
  { label = "&uuml;",   send = "RIGHTALT,^2,U" }
]

[[tab]]
label = "MuseScore"
cols = 4
keys = [
  { label = "Esc",  send = "ESC" },
  { label = ">",    send = "V" },
  { label = "Slur", send = "S" },
  { label = "_",    send = "N" },
#
  { label = "&#x266E;", send = "EQUAL" },  # Natural
  { label = "&#x266F;", send = "^EQUAL" }, # Sharp
  { label = "&#x266D;", send = "MINUS" },  # Flat
  { label = "BLANK" },
#
#  { label = "&#119135;", send = "5" },     # Crotchet
  { label = "&#x2669;", send = "5" },     # Crotchet
  { label = "&#x1D15E;", send = "6" },     # Minim
  { label = "&#x1D15D;", send = "7" },     # Semibreve
  { label = "BLANK" },
#
  { label = "&#x1d162;", send = "2" },     # Demisemiquaver
  { label = "&#x266C;", send = "3" },     # Semiquaver
  { label = "&#x266A;", send = "4" },      # Quaver
  { label = "Tie", rowspan = 2, send = "T" },
#
  { label = "Rest", colspan = 2, send = "0" },
  { label = ".", send = "DOT" }
]

[[tab]]
label = "NumPad"
cols = 4
keys = [
   { label = "Num", send = "NUMLOCK" },
   { label = "/", send = "KPSLASH" },
   { label = "*", send = "KPASTERISK" },
   { label = "-", send = "KPMINUS" },
#
   { label = "7", send = "KP7" },
   { label = "8", send = "KP8" },
   { label = "9", send = "KP9" },
   { label = "+", rowspan = 2, send = "KPPLUS" },
#
   { label = "4", send = "KP4" },
   { label = "5", send = "KP5" },
   { label = "6", send = "KP6" },
#
   { label = "1", send = "KP1" },
   { label = "2", send = "KP2" },
   { label = "3", send = "KP3" },
   { label = "&crarr;", rowspan = 2, send = "KPENTER" },
#
   { label = "0", colspan = 2, send = "KP0" },
   { label = ".", send = "KPDOT" }
]

[[tab]]
label = "Hex"
cols = 4
keys = [
   {label="A",send="A"},{label="B",send="B"},{label="C",send="C"},{label="D",send="D"},
   {label="7",send="7"},{label="8",send="8"},{label="9",send="9"},{label="E",send="E"},
   {label="4",send="4"},{label="5",send="5"},{label="6",send="6"},{label="F",send="F"},
   {label="1",send="1"},{label="2",send="2"},{label="3",send="3"},{label="&crarr;",rowspan=2,send="KPENTER"},
   {label="0",colspan=2,send="0"},{label="#",send="BACKSLASH"}
]