[keypadder]
port = 8082	# HTTP port to use

[[tab]]   # A new tab
label = "French"
cols = 3	# No. of columns on this tab
keys = [
  { label = "&agrave;", send = "COMPOSE,GRAVE,A" },
  { label = "&acirc;",  send = "COMPOSE,^6,A" },
  { label = "&ccedil;", send = "COMPOSE,COMMA,C" },
# new row will start here
  { label = "&egrave;", send = "COMPOSE,GRAVE,E" },
  { label = "&ecirc;",  send = "COMPOSE,^6,E" },
  { label = "&eacute;", send = "COMPOSE,APOSTROPHE,E" },
#
  { label = "&igrave;", send = "COMPOSE,GRAVE,I" },
  { label = "&icirc;",  send = "COMPOSE,^6,I" },
  { label = "&iuml;",   send = "COMPOSE,^2,I" },
#
  { label = "&ograve;", send = "COMPOSE,GRAVE,O" },
  { label = "&ocirc;",  send = "COMPOSE,^6,O" },
  { label = "&euml;",   send = "COMPOSE,^2,E" },
#
  { label = "&ugrave;", send = "COMPOSE,GRAVE,U" },
  { label = "&ucirc;",  send = "COMPOSE,^6,U" },
  { label = "&uuml;",   send = "COMPOSE,^2,U" }
]

[[tab]]
label = "MuseScore"
cols = 4
keys = [
  { label = "Esc",  send = "ESC" },
  { label = ">",    send = "V" },
  { label = "Slur", send = "S" },
  { label = "_",    send = "N" },
#
  { label = "&#x266E;", send = "EQUAL" },
  { label = "&#x266F;", send = "^EQUAL" },
  { label = "&#x266D;", send = "MINUS" },
  { label = "BLANK" },
#
  { label = "&#119135;", send = "5" },
  { label = "&#x1D15E;", send = "6" },
  { label = "&#x1D15D;", send = "7" },
  { label = "BLANK" },
#
  { label = "&#x1d162;", send = "2" },
  { label = "&#x1D161;", send = "3" },
  { label = "&#x1D160;", send = "4" },
  { label = "Tie", rowspan = 2, send = "T" },
#
  { label = "Rest", colspan = 2, send = "0" },
  { label = ".", send = "DOT" }
]

[[tab]]
label = "NumPad"
cols = 4
keys = [
   { label = "Num", send = "NUMLOCK" },
   { label = "/", send = "KPSLASH" },
   { label = "*", send = "KPASTERISK" },
   { label = "-", send = "KPMINUS" },
#
   { label = "7", send = "KP7" },
   { label = "8", send = "KP8" },
   { label = "9", send = "KP9" },
   { label = "+", rowspan = 2, send = "KPPLUS" },
#
   { label = "4", send = "KP4" },
   { label = "5", send = "KP5" },
   { label = "6", send = "KP6" },
#
   { label = "1", send = "KP1" },
   { label = "2", send = "KP2" },
   { label = "3", send = "KP3" },
   { label = "&crarr;", rowspan = 2, send = "KPENTER" },
#
   { label = "0", colspan = 2, send = "KP0" },
   { label = ".", send = "KPDOT" },
]