[keypadder]
port = 8082	            # HTTP port to use (must be set)
tabswitch = "dropdown"  # optional - either  "tabs" or "dropdown"

[[tab]]   # A new tab
label = "French"
cols = 4	# No. of columns on this tab
keys = [
  { label = "&agrave;", send = "RIGHTALT,GRAVE,A" }, # Raw USB keypresses
  { label = "&acirc;",  send = "@,0,0,E,2,SPACE" },  # Unicode method
  { label = "&Agrave;", send = "RIGHTALT,GRAVE,Shift+A" },
  { label = "&ccedil;", send = "RIGHTALT,COMMA,C" },
# new row will start here
  { label = "&egrave;", bg = "Teal",    send = "RIGHTALT,GRAVE,E" },
  { label = "&ecirc;",  send = "RIGHTALT,Shift+6,E" },    
  { label = "&eacute;", bg = "#008800", send = "RIGHTALT,APOSTROPHE,E" },
  { label = "&euml;",   send = "RIGHTALT,Shift+2,E" },
#
  { label = "&igrave;", send = "RIGHTALT,GRAVE,I" },
  { label = "&icirc;",  send = "RIGHTALT,Shift+6,I" },
  { label = "&iuml;",   send = "RIGHTALT,Shift+2,I" },
  { label = "BLANK" },
#
  { label = "&ograve;", send = "RIGHTALT,GRAVE,O" },
  { label = "&ocirc;",  send = "RIGHTALT,Shift+6,O" },
  { label = "&Ocirc;",  send = "RIGHTALT,Shift+6,Shift+O" },
  { label = "&oelig;",  send = "@,0,1,5,3,SPACE" },
#
  { label = "&ugrave;", send = "RIGHTALT,GRAVE,U" },
  { label = "&ucirc;",  send = "RIGHTALT,Shift+6,U" },
  { label = "&uuml;",   send = "RIGHTALT,Shift+2,U" },
  { label = "&euro;",   bg = "Gold", send = "@,2,0,A,C,SPACE"}
]

[[tab]]
label = "MuseScore"
cols = 4
keys = [
  { label = "Esc", send = "ESC" },
  { label = ">",   send = "V" },
  { label = ".",   send = "Shift+S" },
  { label = "_",   send = "N" },
#
  { label = "&#x266e;", send = "EQUAL" },  # Natural
  { label = "&#x266f;", send = "Shift+EQUAL" }, # Sharp
  { label = "&#x266d;", send = "MINUS" },  # Flat
  { label = "Save",     send = "Ctrl+S" },     # Save
#
  { label = "&#x2669;",  send = "5" },     # Crotchet
  { label = "&#x1d15e;", send = "6" },     # Minim
  { label = "&#x1d15d;", send = "7" },     # Semibreve
  { label = "Redo",      send = "Ctrl+Shift+Z" },   # Redo
#
  { label = "&#x1d162;", send = "2" },     # Demisemiquaver
  { label = "&#x266c;",  send = "3" },     # Semiquaver
  { label = "&#x266a;",  send = "4" },     # Quaver
  { label = "Tie", rowspan = 2, send = "T" },
#
  { label = "Rest", colspan = 2, send = "0" },
  { label = ".", send = "DOT" }
]

[[tab]]
label = "Hex"
cols = 4
keys = [
   {label="A",send="A"},{label="B",send="B"},{label="C",send="C"},{label="D",send="D"},
   {label="7",send="7"},{label="8",send="8"},{label="9",send="9"},{label="E",send="E"},
   {label="4",send="4"},{label="5",send="5"},{label="6",send="6"},{label="F",send="F"},
   {label="1",send="1"},{label="2",send="2"},{label="3",send="3"},{label="&crarr;",rowspan=2,send="KPENTER"},
   {label="0",colspan=2,send="0"},{label="#",send="BACKSLASH"}
]

[[tab]]
label ="Emojis"
cols = 4
keys = [
   {label="&#x1f600;", send="@,1,F,6,0,0,SPACE"}, # grinning face
   {label="&#x1f602;", send="@,1,F,6,0,2,SPACE"}, # face with tears of joy
   {label="&#x1f61f;", send="@,1,F,6,1,F,SPACE"}, # worried face
   {label="&#x1f609;", send="@,1,F,6,0,9,SPACE"}, # winking face
#
   {label="&#x1f92d;", send="@,1,F,9,2,D,SPACE"}, # face with hand over mouth
   {label="&#x1f92b;", send="@,1,F,9,2,B,SPACE"}, # shushing face
   {label="&#x1f914;", send="@,1,F,9,1,4,SPACE"}, # thinking face
   {label="&#x1f928;", send="@,1,F,9,2,8,SPACE"}, # zipper-mouth face
 #
   {label="&#x1f37e;", send="@,1,F,3,7,E,SPACE"}, # popping cork
   {label="&#x1f377;", send="@,1,F,3,7,7,SPACE"}, # glass of wine
   {label="&#x1f378;", send="@,1,F,3,7,8,SPACE"}, # cocktail
   {label="&#x1f37a;", send="@,1,F,3,7,A,SPACE"}, # beer   
#
   {label="&#x1f3b7;", send="@,1,F,3,B,7,SPACE"}, # sax
   {label="&#x1f3b9;", send="@,1,F,3,B,9,SPACE"}, # keyboard
   {label="&#x1f3bb;", send="@,1,F,3,B,B,SPACE"}, # violin
   {label="&#x1f941;", send="@,1,F,9,4,1,SPACE"}, # side-drum
#
   {label="&#x1f436;", send="@,1,F,4,3,6,SPACE"}, # dog face
   {label="&#x1f431;", send="@,1,F,4,3,1,SPACE"}, # cat face
   {label="&#x1f44d;", send="@,1,F,4,4,D,SPACE"}, # thumbs-up
   {label="&#x1f44e;", send="@,1,F,4,4,E,SPACE"}, # thumbs-down
]


[[tab]]
label = "Multimedia"
cols = 3
keys = [
  { label = "&#x23EE;",  send = "PREVIOUSSONG" },
  { label = "&#x23EF;",  send = "PLAYPAUSE" },
  { label = "&#x23ED;",  send = "NEXTSONG" },
  { label = "&#x1F3A6;", send = "MEDIA" },
  { label = "&#x23EA;",  send = "LEFT" },
  { label = "&#x23E9;",  send = "RIGHT" },
  { label = "&#x1F508;", send = "VOLUMEDOWN" },
  { label = "&#x1F50A;", send = "VOLUMEUP" },
  { label = "&#x1F507;", send = "MUTE" },
  { label = "&#x1F505;", send = "BRIGHTNESSDOWN" },
  { label = "&#x1F506;", send = "BRIGHTNESSUP" },
  { label = "&#x1F5A5;", send = "SWITCHVIDEOMODE" },
]

[[tab]]
label = "LibreOffice" # Testing all the modifiers
cols = 2
fontsize = "20pt"
keys = [
   { label = "Help",           send = "F1" },
   { label = "Options",        send = "Alt+F12" },
   { label = "Spelling",       send = "Shift+F7" },
   { label = "Thesaurus",      send = "Ctrl+F7" },
   { label = "As Currency",    send = "Ctrl+Shift+4" },
   { label = "As Percentage",  send = "Ctrl+Shift+5" },
   { label = "Comment",        send = "Ctrl+Alt+C" },
   { label = "Paste&NewLine;Unformatted",  send = "Ctrl+Alt+Shift+V" },
]

[[tab]]
label = "Applications"
cols = 2
fontsize = "28pt"
keys = [
   # {label="Archive",    send="ARCHIVE"},
   # {label="Audio",      send="AUDIO"},
   # {label="BlueTooth",  send="BLUETOOTH"},
   {label="Calculator", send="CALC"},
   # {label="Calendar",   send="CALENDAR"},
   # {label="Camera",     send="CAMERA"},
   # {label="Chat",       send="CHAT"},
   # {label="Contacts",   send="ADDRESSBOOK"},
   # {label="Edit",       send="EDIT"},
   # {label="Editor",     send="EDITOR"},
   {label="Email",      send="EMAIL"},
   {label="File",       send="FILE"},
   # {label="Graphics",   send="GRAPHICSEDITOR"},
   # {label="Images",     send="IMAGES"},
   # {label="Player",     send="PLAYER"},
   # {label="Presentation", send="PRESENTATION"},
   {label="Run",        send="Alt+F2"},
   {label="ScreenLock", send="SCREENLOCK"},
   # {label="Search",     send="SEARCH"},
   # {label="Sound",      send="SOUND"},
   # {label="Spreadsheet",  send="SPREADSHEET"},
   # {label="Task Mgr",     send="TASKMANAGER"},
   {label="Terminal",   send="Ctrl+Alt+T"},
   {label="Tuner",      send="TUNER"},
   # {label="Video",      send="VIDEO"},
   # {label="Word Proc.",   send="WORDPROCESSOR"},
   {label="WWW",        send="WWW"},
]