[keypadder]
port = 8082	# HTTP port to use

[[tab]]   # A new tab
label = "French"
cols = 3	# No. of columns on this tab
keys = [
  { label = "&agrave;", send  = "à" },
  { label = "&acirc;",  send = "â" },
  { label = "&ccedil;", send = "ç" },
# new row will start here
  { label = "&egrave;", send = "è" },
  { label = "&ecirc;",  send = "ê" },
  { label = "&eacute;", send = "é" },
#
  { label = "&igrave;", send = "ì" },
  { label = "&icirc;",  send = "î" },
  { label = "&iuml;",   send = "ï" },
#
  { label = "&ograve;", send = "ò" },
  { label = "&ocirc;",  send = "ô" },
  { label = "&euml;",   send = "ë" },
#
  { label = "&ugrave;", send = "ù" },
  { label = "&ucirc;",  send = "û" },
  { label = "&uuml;",   send = "ü" }
]

[[tab]]
label = "MuseScore"
cols = 4
keys = [
  { label = "Esc", send = "\u001b" },
  { label = ">",   send = "V" },
  { label = "Slur", send = "S" },
  { label = "_", send = "N" },
#
  { label = "&#x266E;", send = "=" },
  { label = "&#x266F;", send = "+" },
  { label = "&#x266D;", send = "-" },
  { label = "BLANK" },
#
  { label = "&#119135;", send = "5" },
  { label = "&#x1D15E;", send = "6" },
  { label = "&#x1D15D;", send = "7" },
  { label = "BLANK" },
#
  { label = "&#x1d162;", send = "2" },
  { label = "&#x1D161;", send = "3" },
  { label = "&#x1D160;", send = "4" },
  { label = "Tie", rowspan = 2, send = "T" },
#
  { label = "Rest", colspan = 2, send = "0" },
  { label = "." }
]
